(() => {
'use strict';
const OWNER='45c5cfc7-090e-491f-a304-05f863bbdf85', BUCKET='tutorial-media', PAGE=18;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:''}catch{return ''}};
const models=window.TUTORIAL_MODELS, modelFor=b=>models.find(m=>m.id===b.model);
let sb,owner=false,record=null,dirty=false,busy=false,offset=0,toastTimer,authId=null;
const status=(message,error=false)=>{const el=$('#status');el.textContent=message;el.classList.toggle('error',error)};
const toast=message=>{$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,2400)};
function mark(){dirty=true;const s=$('#save-state');if(s)s.textContent='Unsaved changes'}
function image(url,alt,cls=''){const u=safeUrl(url);return u?`<img class="${cls}" src="${esc(u)}" alt="${esc(alt)}" loading="lazy" decoding="async">`:''}
function media(b){const u=safeUrl(b.url);if(!u)return '';const width=Math.max(25,Math.min(100,Number(b.width)||100));return `<figure class="visual" style="width:${width}%">${b.type==='video'?`<video src="${esc(u)}" controls playsinline preload="none"></video>`:image(u,b.caption||'Tutorial image')} ${b.caption?`<figcaption class="muted">${esc(b.caption)}</figcaption>`:''}</figure>`}
function blocksMarkup(blocks){return blocks.map(b=>`<section class="block">${b.type==='headline'?`<h2>${esc(b.text)}</h2>`:b.type==='image'||b.type==='video'?media(b):b.type==='prompt'?`<div class="prompt-box"><div class="prompt-bar"><strong><span class="prompt-icon">✦</span>${esc(modelFor(b)?.name||'Prompt')}</strong><div class="actions"><button data-copy="${esc(b.id)}">Copy</button><button class="purple" data-recreate="${esc(b.id)}">Recreate ↗</button></div></div><pre class="prompt-text">${esc(b.text)}</pre>${(b.refs||[]).length?`<div class="refs">${b.refs.map((u,i)=>`<div class="ref">${image(u,'Reference '+(i+1))}<span>Image ${i+1}</span></div>`).join('')}</div>`:''}</div>`:''}</section>`).join('')}
async function gallery(reset=false){
 if(busy)return;busy=true;$('#more').disabled=true;
 try{if(reset){offset=0;$('#gallery').innerHTML=''}status('Loading examples…');
 let q=sb.from('tutorials').select('id,title,cover_url,published,created_at').order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+PAGE);
 if(!owner)q=q.eq('published',true);
 const {data,error}=await q;if(error)throw error;
 $('#gallery').insertAdjacentHTML('beforeend',data.slice(0,PAGE).map(t=>`<a class="card" href="tutorial.html?id=${encodeURIComponent(t.id)}">${image(t.cover_url,t.title)}<h2>${esc(t.title)}</h2>${!t.published?'<span class="badge">Draft · Only you</span>':''}</a>`).join(''));
 offset+=Math.min(data.length,PAGE);$('#more').hidden=data.length<=PAGE;status('');
 if(!offset)$('#gallery').innerHTML='<div class="empty">No tutorials published yet.</div>';
 }catch(e){status('Could not load examples. '+e.message,true)}finally{busy=false;$('#more').disabled=false}
}
function renderReader(){document.title=record.title+' · Hansora';$('#reader').innerHTML=`<div class="top"><h1>${esc(record.title)}</h1>${owner?'<button id="edit">Edit tutorial</button>':''}</div>${!record.published?'<p class="badge">Draft · Only you</p>':''}${image(record.cover_url,record.title,'cover')}${blocksMarkup(record.blocks)}`;$('#editor').hidden=true;$('#reader').hidden=false;$('#edit')?.addEventListener('click',editor)}
const options=(items,value)=>items.map(x=>`<option value="${esc(x)}" ${String(x)===String(value)?'selected':''}>${esc(x||'Model default')}</option>`).join('');
function select(label,field,items,value){return `<label>${label}<select data-field="${field}">${options(items,value)}</select></label>`}
function modelSettings(b){const m=modelFor(b);return `<label>Generation model<select data-field="model">${models.map(m=>`<option value="${esc(m.id)}" ${m.id===b.model?'selected':''}>${esc(m.name)} · ${m.category}</option>`).join('')}</select></label><div class="fields">${select('Aspect ratio','aspectRatio',m?.aspects||[],b.aspectRatio)}${select('Resolution','resolution',['',...(m?.resolutions||[])],b.resolution)}${m?.durations.length?select('Duration (seconds)','duration',m.durations,b.duration):''}</div><label>Prompt<textarea data-field="text" placeholder="Write your prompt…">${esc(b.text)}</textarea></label><label>Reference images · ${m?.maxFiles||0} maximum<input type="file" data-upload="refs" accept="image/jpeg,image/png,image/webp" multiple ${!m?.maxFiles?'disabled':''}></label><p class="muted">These images are inserted with the prompt when someone clicks Recreate. Their order matches Image 1, Image 2, and so on.</p><div class="refs">${(b.refs||[]).map((u,i)=>`<div class="ref">${image(u,'Reference '+(i+1))}<span>Image ${i+1}</span><button data-remove-ref="${i}" aria-label="Remove reference ${i+1}">×</button>${i?`<button data-ref-left="${i}" aria-label="Move reference ${i+1} left">←</button>`:''}</div>`).join('')}</div>`}
function blockEditor(b,i){return `<section class="editor-block" data-block="${esc(b.id)}"><div class="block-tools"><strong>${i+1}. ${esc(b.type==='headline'?'Headline':b.type==='prompt'?'Prompt':b.type==='video'?'Video':'Image')}</strong><div class="actions"><button data-move="-1" ${!i?'disabled':''} aria-label="Move section up">↑</button><button data-move="1" ${i===record.blocks.length-1?'disabled':''} aria-label="Move section down">↓</button><button data-remove aria-label="Remove section">×</button></div></div>${b.type==='headline'?`<label>Headline<input class="title-input" data-field="text" value="${esc(b.text)}" placeholder="Section headline"></label>`:b.type==='prompt'?modelSettings(b):`<label>Upload ${b.type}<input type="file" data-upload="media" accept="${b.type==='video'?'video/mp4,video/webm,video/quicktime':'image/jpeg,image/png,image/webp,image/gif,image/avif'}"></label>${media(b)}<label>Display width: <span data-width-label>${b.width}%</span><input type="range" min="25" max="100" step="5" data-field="width" value="${b.width}"></label><label>Caption (optional)<input data-field="caption" value="${esc(b.caption||'')}"></label>`}</section>`}
function renderBlocks(){ $('#blocks').innerHTML=record.blocks.map(blockEditor).join('') }
function editor(){if(!owner)return;$('#reader').hidden=true;$('#editor').hidden=false;$('#editor').innerHTML=`<div class="top"><h1>${record.created_at?'Edit tutorial':'New tutorial'}</h1><button id="preview-toggle">Preview</button></div><div class="editor-head"><label>Tutorial title<input id="title" class="title-input" maxlength="300" value="${esc(record.title)}" placeholder="Name your tutorial"></label><label>Cover image · also shown in Examples<input id="cover-upload" type="file" accept="image/jpeg,image/png,image/webp"></label><div id="cover-preview">${image(record.cover_url,'Cover','editor-image')}</div></div><div id="blocks"></div><div class="add-menu"><strong>Add a section</strong><button data-add="headline">＋ Headline</button><button data-add="image">＋ Image</button><button data-add="video">＋ Video</button><button data-add="prompt">＋ Prompt</button></div><div class="save-bar"><label><input id="published" type="checkbox" ${record.published?'checked':''}> Published</label><span class="muted" id="save-state">${dirty?'Unsaved changes':'Saved'}</span><button id="save" class="primary">Save tutorial</button><button id="done">Done</button></div><div id="preview" hidden></div>`;renderBlocks();
 $('#title').addEventListener('input',e=>{record.title=e.target.value;mark()});$('#published').addEventListener('change',e=>{record.published=e.target.checked;mark()});$('#save').addEventListener('click',save);$('#done').addEventListener('click',()=>{if(dirty){toast('Save your changes first.');return}if(!record.created_at){location.href='examples.html';return}renderReader()});$('#preview-toggle').addEventListener('click',()=>{const p=$('#preview');p.hidden=!p.hidden;if(!p.hidden){p.innerHTML=`<h1>${esc(record.title||'Untitled tutorial')}</h1>${image(record.cover_url,'Cover','cover')}${blocksMarkup(record.blocks)}`;p.scrollIntoView({behavior:'smooth'})}});
}
async function optimizeCover(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use a JPEG, PNG, or WebP cover image.');
 if(file.size>20*1024*1024)throw Error('Cover image must be smaller than 20 MB.');
 const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1200/bitmap.width);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',0.82));if(!blob)throw Error('Could not prepare cover image.');return new File([blob],'cover.webp',{type:blob.type})}finally{bitmap.close()}
}
async function upload(file,kind,maxMB=100){if(!owner)throw Error('Sign in with the owner account.');const allowed=kind==='video'?['video/mp4','video/webm','video/quicktime']:['image/jpeg','image/png','image/webp','image/gif','image/avif'];if(!allowed.includes(file.type))throw Error('Unsupported file type. Use a supported image or MP4/WebM video.');if(file.size>maxMB*1024*1024)throw Error('File must be smaller than '+maxMB+' MB.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','image/avif':'avif','video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'}[file.type];const path=record.id+'/'+crypto.randomUUID()+'.'+ext;const {error}=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(error)throw Error('Upload failed. '+error.message);return sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
function validate(){if(!record.title.trim())throw Error('Add a tutorial title.');if(!safeUrl(record.cover_url))throw Error('Upload a cover image.');if(!record.blocks.length&&record.published)throw Error('Add a section before publishing.');for(const [i,b] of record.blocks.entries()){const label='Section '+(i+1)+': ';if(['headline','prompt'].includes(b.type)&&!b.text.trim())throw Error(label+'add text.');if(['image','video'].includes(b.type)&&!safeUrl(b.url))throw Error(label+'upload your '+b.type+'.');if(b.type==='prompt'){const m=modelFor(b);if(!m)throw Error(label+'choose a model.');if(b.refs.length>m.maxFiles)throw Error(label+'too many reference images for this model.');if(m.needsImage&&!b.refs.length)throw Error(label+'this model requires a reference image.')}}}
async function save(){if(!owner||busy)return;try{validate();busy=true;$('#editor').inert=true;$('#save').disabled=true;status('Saving…');const now=new Date().toISOString();const payload={id:record.id,title:record.title.trim(),cover_url:record.cover_url,blocks:record.blocks,published:record.published,updated_at:now};let q=record.created_at?sb.from('tutorials').update(payload).eq('id',record.id).eq('updated_at',record.updated_at):sb.from('tutorials').insert(payload);const {data,error}=await q.select().maybeSingle();if(error)throw error;if(!data)throw Error('This tutorial changed in another tab, or your editing permission changed. Reload before saving.');record=data;dirty=false;history.replaceState({},'',`tutorial.html?id=${record.id}`);$('#save-state').textContent='Saved';status('');toast(record.published?'Tutorial published':'Draft saved')}catch(e){status(e.message,true)}finally{busy=false;if($('#editor'))$('#editor').inert=false;if($('#save'))$('#save').disabled=false}}
async function recreate(b){if(!modelFor(b)){toast('This model is unavailable.');return}try{sessionStorage.setItem('hansora:article-preset',JSON.stringify({model:b.model,prompt:b.text,referenceImageUrls:b.refs||[],aspectRatio:b.aspectRatio,resolution:b.resolution||null,duration:b.duration?Number(b.duration):null}));location.href='/search-models.html?model='+encodeURIComponent(b.model)+'&articlePreset=1'}catch{toast('Your browser could not save the prompt. Allow site storage and try again.')}}
document.addEventListener('input',e=>{const el=e.target,b=record?.blocks.find(b=>b.id===el.closest('[data-block]')?.dataset.block);if(!owner||!b||!el.dataset.field||el.dataset.field==='model')return;const f=el.dataset.field;b[f]=['width','duration'].includes(f)?Number(el.value):el.value;mark();if(f==='width'){const host=el.closest('[data-block]');host.querySelector('[data-width-label]').textContent=b.width+'%';const v=host.querySelector('.visual');if(v)v.style.width=b.width+'%'}});
document.addEventListener('change',async e=>{const el=e.target;if(!owner||busy)return;const b=record?.blocks.find(b=>b.id===el.closest('[data-block]')?.dataset.block);if(el.dataset.field==='model'&&b){const m=models.find(m=>m.id===el.value);Object.assign(b,{model:m.id,aspectRatio:m.defaultAspect,resolution:m.defaultResolution,duration:m.durations[0]||null});mark();renderBlocks();return}if(!el.matches('[data-upload],#cover-upload')||!el.files.length)return;busy=true;$('#editor').inert=true;status('Uploading…');try{if(el.id==='cover-upload'){record.cover_url=await upload(await optimizeCover(el.files[0]),'image',20);$('#cover-preview').innerHTML=image(record.cover_url,'Cover','editor-image')}else if(el.dataset.upload==='refs'){const m=modelFor(b);if(b.refs.length+el.files.length>m.maxFiles)throw Error('This model supports up to '+m.maxFiles+' reference images.');for(const f of el.files){b.refs.push(await upload(f,'image',Math.min(100,m.uploadMaxMB)));mark()}}else b.url=await upload(el.files[0],b.type,b.type==='image'?20:100);mark();status('');}catch(err){status(err.message,true)}finally{busy=false;$('#editor').inert=false;el.value='';renderBlocks()}});
document.addEventListener('click',async e=>{const btn=e.target.closest('button');if(!btn)return;const block=record?.blocks.find(b=>b.id===btn.closest('[data-block]')?.dataset.block);if(btn.hasAttribute('data-copy')){const b=record.blocks.find(b=>b.id===btn.dataset.copy);try{await navigator.clipboard.writeText(b.text);toast('Prompt copied')}catch{toast('Copy failed. Select and copy the prompt text.')}return}if(btn.hasAttribute('data-recreate')){if(dirty&&!confirm('Leave with unsaved changes to try this prompt?'))return;await recreate(record.blocks.find(b=>b.id===btn.dataset.recreate));return}if(!owner||busy)return;if(btn.dataset.add){const type=btn.dataset.add,m=models.find(m=>m.id==='nano-banana-2');record.blocks.push({id:crypto.randomUUID(),type,...(type==='prompt'?{text:'',model:m.id,refs:[],aspectRatio:m.defaultAspect,resolution:m.defaultResolution,duration:null}:type==='headline'?{text:''}:{url:'',width:100,caption:''})});mark();renderBlocks();$('#blocks').lastElementChild.scrollIntoView({behavior:'smooth',block:'center'})}else if(block){const i=record.blocks.indexOf(block);if(btn.hasAttribute('data-remove')){if(!confirm('Remove this section?'))return;record.blocks.splice(i,1)}else if(btn.dataset.move){const next=i+Number(btn.dataset.move);if(next<0||next>=record.blocks.length)return;[record.blocks[i],record.blocks[next]]=[record.blocks[next],record.blocks[i]]}else if(btn.hasAttribute('data-remove-ref'))block.refs.splice(Number(btn.dataset.removeRef),1);else if(btn.hasAttribute('data-ref-left')){const j=Number(btn.dataset.refLeft);[block.refs[j-1],block.refs[j]]=[block.refs[j],block.refs[j-1]]}else return;mark();renderBlocks()}});
document.addEventListener('click',e=>{if(e.target.matches('.visual img,.refs img,.cover')&&$('#lightbox')){$('#large-image').src=e.target.src;$('#large-image').alt=e.target.alt;$('#lightbox').showModal()}});$('#close-lightbox')?.addEventListener('click',()=>$('#lightbox').close());$('#lightbox')?.addEventListener('click',e=>{if(e.target===$('#lightbox'))$('#lightbox').close()});window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});
async function loadTutorial(){const p=new URLSearchParams(location.search);if(p.get('new')==='1'){if(!owner){status('Sign in with your owner account to create a tutorial.',true);return}record={id:crypto.randomUUID(),title:'',cover_url:'',blocks:[],published:false};status('');editor();return}const id=p.get('id');if(!id){status('Choose a tutorial from Examples.',true);return}const {data,error}=await sb.from('tutorials').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data){status('This tutorial is unavailable or has not been published.',true);return}record=data;record.blocks=Array.isArray(record.blocks)?record.blocks:[];status('');renderReader()}
async function init(){try{if(!window.supabase)throw Error('Connection library did not load. Refresh to try again.');sb=window.__HANSORA_SB__||window.hansoraSupabase;if(!sb)throw Error('The shared header did not initialize. Check that /header.js is installed.');const {data:{user}}=await sb.auth.getUser();authId=user?.id||null;owner=authId===OWNER;if($('#gallery')){$('#new').hidden=!owner;$('#new').onclick=()=>location.href='tutorial.html?new=1';$('#more').onclick=()=>gallery();await gallery()}else await loadTutorial();sb.auth.onAuthStateChange((event,session)=>{const next=session?.user?.id||null;if(next===authId)return;authId=next;owner=next===OWNER;if(!owner){dirty=false;$('#editor')?.replaceChildren();if($('#editor'))$('#editor').hidden=true}setTimeout(()=>location.reload(),0)})}catch(e){status(e.message,true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
