-- Hansora Automation: business tools (booking calendar, orders, leads, handoff) and owner notifications.
-- Apply after 20260927_automation_core.sql and 20260927_automation_runtime.sql.

create extension if not exists btree_gist;

-- Outcomes created by AI tools are retried safely and get a short number the owner and customer can quote.
alter table automation.automation_outcomes
  add column if not exists reference_number bigint generated by default as identity,
  add column if not exists idempotency_key text check (idempotency_key is null or char_length(idempotency_key) <= 300),
  add column if not exists customer_name text not null default '' check (char_length(customer_name) <= 200),
  add column if not exists customer_phone text not null default '' check (char_length(customer_phone) <= 60),
  add column if not exists service_name text not null default '' check (char_length(service_name) <= 200),
  add column if not exists assignee text not null default '' check (char_length(assignee) <= 120);

create unique index if not exists automation_outcomes_idempotency_idx
  on automation.automation_outcomes (business_id, idempotency_key) where idempotency_key is not null;
create unique index if not exists automation_outcomes_reference_idx
  on automation.automation_outcomes (reference_number);
create index if not exists automation_outcomes_schedule_idx
  on automation.automation_outcomes (business_id, scheduled_start) where outcome_type = 'booking';

-- The database itself refuses two active bookings in the same business time range,
-- so two customers booking the last slot at the same moment cannot both succeed.
alter table automation.automation_outcomes drop constraint if exists automation_outcomes_no_double_booking;
alter table automation.automation_outcomes add constraint automation_outcomes_no_double_booking
  exclude using gist (business_id with =, tstzrange(scheduled_start, scheduled_end, '[)') with &&)
  where (outcome_type = 'booking' and status in ('new', 'in_progress', 'waiting', 'confirmed') and scheduled_start is not null and scheduled_end is not null);

alter table automation.automation_outcomes drop constraint if exists automation_outcomes_booking_times;
alter table automation.automation_outcomes add constraint automation_outcomes_booking_times
  check (outcome_type <> 'booking' or (scheduled_start is not null and scheduled_end is not null));

-- Owner notification preferences. WhatsApp numbers are written only by the server after code verification.
create table if not exists automation.automation_notification_settings (
  business_id uuid primary key references automation.automation_businesses(id) on delete cascade,
  whatsapp_enabled boolean not null default false,
  whatsapp_phone text check (whatsapp_phone is null or whatsapp_phone ~ '^[1-9][0-9]{7,14}$'),
  whatsapp_verified_at timestamptz,
  email_enabled boolean not null default true,
  email text check (email is null or (char_length(email) <= 320 and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')),
  events text[] not null default array['order_created', 'booking_created', 'handoff_requested']::text[],
  language text not null default 'en' check (language in ('en', 'hy', 'ru')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (events <@ array['order_created', 'booking_created', 'booking_cancelled', 'handoff_requested', 'lead_created']::text[]),
  check (not whatsapp_enabled or whatsapp_verified_at is not null)
);

create table if not exists automation.automation_notification_verifications (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references automation.automation_businesses(id) on delete cascade,
  phone text not null check (phone ~ '^[1-9][0-9]{7,14}$'),
  code_hash text not null check (char_length(code_hash) = 64),
  attempts integer not null default 0 check (attempts between 0 and 10),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists automation_notification_verifications_business_idx
  on automation.automation_notification_verifications (business_id, created_at desc);

create table if not exists automation.automation_notification_deliveries (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references automation.automation_businesses(id) on delete cascade,
  outcome_id uuid references automation.automation_outcomes(id) on delete set null,
  conversation_id uuid references automation.automation_conversations(id) on delete set null,
  event_type text not null check (event_type in ('order_created', 'booking_created', 'booking_cancelled', 'handoff_requested', 'lead_created', 'test')),
  channel text not null check (channel in ('whatsapp', 'email')),
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skipped')),
  provider_message_id text check (provider_message_id is null or char_length(provider_message_id) <= 500),
  error text check (error is null or char_length(error) <= 2000),
  idempotency_key text not null check (char_length(idempotency_key) <= 300),
  created_at timestamptz not null default now(),
  unique (business_id, idempotency_key)
);
create index if not exists automation_notification_deliveries_business_idx
  on automation.automation_notification_deliveries (business_id, created_at desc);

alter table automation.automation_notification_settings enable row level security;
alter table automation.automation_notification_verifications enable row level security;
alter table automation.automation_notification_deliveries enable row level security;

drop policy if exists automation_notification_settings_owner_read on automation.automation_notification_settings;
create policy automation_notification_settings_owner_read on automation.automation_notification_settings
  for select to authenticated using (automation.automation_owns_business(business_id));
drop policy if exists automation_notification_deliveries_owner_read on automation.automation_notification_deliveries;
create policy automation_notification_deliveries_owner_read on automation.automation_notification_deliveries
  for select to authenticated using (automation.automation_owns_business(business_id));

grant select on automation.automation_notification_settings to authenticated;
grant select on automation.automation_notification_deliveries to authenticated;
revoke all on automation.automation_notification_settings from anon;
revoke all on automation.automation_notification_deliveries from anon;
revoke all on automation.automation_notification_verifications from public, anon, authenticated;

-- Server functions use the service role, which needs explicit rights in the automation schema.
grant all on all tables in schema automation to service_role;
grant all on all sequences in schema automation to service_role;
grant execute on all functions in schema automation to service_role;
